name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99f14a5f92dddd8cd333996728fac405d8e8a62bfa72bdd911eabf17315a71ba"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
