name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f74cb099b870ea5a19f80e578c34dde7253a06ab608015deedfda97bcdee5551"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
