name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ecf0536b81d4896425e9645449cb4a9fee1a0321f52cfc1a33f6cce07720a14"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
