name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a72042f7d0cea8c83a0bb09ab48436025707c1446a613ccb20bbeb840a8e3aa5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
