name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1097e887a1e88fc4ab2479a78ddde05c43fc30fbf2bccdb06abdfb2a6baf5471"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
