name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a8f21635766f115318b9ca305762b86a36eb860c8c1631bff1a4d3644f81b23"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
