name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f5b0ef7cad811771dc2ba2f5f19481dc9248b9bcd06af9889e167db028139a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
