name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be3830e95f8180611ba78c71acb4f849e17ed461339cbdf7b8a73821d840d759"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
