name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d34b8ffb80d074f6a8b02544b800e1c2d780c50cb6bf7c758a4484719c0f999"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
