name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc5638246090dac9b2d83d3e6842bafa9327665cdbdc7fbfd3fc8e943c3c834d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
