name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3adfb87c77fe8b6635e3e540839963b4d52accb7907b68497767c394470ad007"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
