name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4ddf0f0fdaf0af5f2da1bbf1db41c04521f80e97b8c611bb82714065993f073"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
