name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ebe7915118842cd0e29209f9fc72db441c89ddf59cb0de7ed566cdf0616c16d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
