name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5710fa22bf475552d1792e104e00c515c91e8f54854759a62ebb57fd7336c6d6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
