name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6897ec60e4c5e63ce915866e2a5735bc6855be998e8bc907e37be7db7006571"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
