name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a5071c6ad9db6531c2963eebc56a1e1781f64313bfb5e1fe18dc47fc648e490"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
