name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb55547df441293db7f517b6cfd1e4824c028730e37b677efa9a52c75b220fc6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
