name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae549a04f2bddaa5e5d8066cc55b326e79741bdc10ec9826bf12572c3a76bc91"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
