name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1e4487c815efb1184825b39ed11f60781409b4fa547c9cee5059052dc3301eb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
