name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c80bbe47677fb4efbf619b66f2f1c2bcaaa496a1bc2b62ec4befbd767b956753"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
