name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11271326ae6d636c200e629326e26db6debecc87f79c28b7b943fa009491893f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
