name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "006dadd425809b9bf204cdb0bc7e922c48726e12388f699490b5d64a68fb6925"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
