name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc8bb144c92387f7cb5f29d1776beb55c640c78fa2b81ef2ad5be816d1498bb6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
