name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a5290bfc30b2207e8fc8b354f0078959eb28e9c1e378bcaf335fef6cbe4cd54"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
