name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36112bba01128413c1c55df24fd6d15bffe53e9695f394b78442b0a1993ee7f6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
