name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da7280b27b634ee4ce02f91ce8176cfef7e384b2dececfb701a2562d120b6268"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
