name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c67a450835cada966310f085efdd1d747077fe18b538ff2987939c251ae626d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
