name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99031c3a1cce7d712a6da2777861c71691aaf67586b77be6b5d50f2d4b91f5d5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
