name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5522be1343b3d6f24322468a9c2026d8a906b5d3113b2768bfbd79296b7ccba1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
