name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e039b77d1a1cdf71f698430a2b708f3d45684ecb31873f887c4095c634bb9c9c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
