name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1de5f3100d5c5d43734a0bd63dad3151090b163e550a693067d7ea0913c9eec6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
