name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23c0de59de26c23d6eba8161cb50088ba2719ea6725180e408eeb3ce218398e8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
