name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c39caf59b08e41553cd8b0191f0f96ed2bea69c182589ab80114b8477a6b50db"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
