name = "vmp"
author = "xoldrin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20e351dd55a84674d2cfd55ad53b96dee84e590da97c5bf7c8bab977ca5fc066"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.201"
